POST http://127.0.0.1:8000/user/ HTTP/1.1
content-type: application/json

{
    "username": "Max",
    "email": "test@email.com",
    "password": "TestPass",
    "full_name": "Maxim"
}

###
GET http://127.0.0.1:8000/items/item2 HTTP/1.1
content-type: application/json

###

GET http://127.0.0.1:8000/default-items/ HTTP/1.1
content-type: application/json

###
GET http://127.0.0.1:8000/keyword-weights/ HTTP/1.1
content-type: application/json

###
